// <auto-generated />
using System;
using Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(CustomDatabaseContext))]
    [Migration("20240731201035_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Backend.Models.CDT2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataString")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceId");

                    b.ToTable("CDT2Table");
                });

            modelBuilder.Entity("Backend.Models.DefaultDataType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataString")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DefaultDataTable");
                });

            modelBuilder.Entity("Backend.Models.CDT2", b =>
                {
                    b.HasOne("Backend.Models.DefaultDataType", "Reference")
                        .WithMany()
                        .HasForeignKey("ReferenceId");

                    b.Navigation("Reference");
                });
#pragma warning restore 612, 618
        }
    }
}
